services:
  - type: web
    name: hcs-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT
